CREATE TABLE TEACHER (
  id INTEGER NOT NULL  AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  age INTEGER NOT NULL,
  nationality VARCHAR(2) NOT NULL,
  membership VARCHAR(1) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(nationality) REFERENCES NATIONALITY(COUNTRY_CODE),
  FOREIGN KEY(membership) REFERENCES MEMBERSHIP(MEMBERSHIP_CODE)
);

CREATE TABLE NATIONALITY(
  COUNTRY_CODE VARCHAR(2) NOT NULL,
  COUNTRY_DESC VARCHAR(20) NOT NULL,
  PRIMARY KEY(COUNTRY_CODE)
);

CREATE TABLE MEMBERSHIP(
  MEMBERSHIP_CODE VARCHAR(1) NOT NULL,
  MEMBERSHIP_DESC VARCHAR(2) NOT NULL,
  PRIMARY KEY(MEMBERSHIP_CODE)
);

CREATE TABLE class(
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL DEFAULT 'N/A',
  PRIMARY KEY(id),
);

CREATE TABLE student(
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT nULL,
  class_id INTEGER DEFAULT NULL,
  gender VARCHAR(6) NOT NULL,
  PRIMARY KEY(id),
  FOREIGHN KEY(class_id) REFERENCES class(id)
);

CREATE TABLE class_teacher(
  id INTEGER NOT NULL AUTO_INCREMENT,
  class_id NOT NULL INTEGER,
  teacher_id NOT NULL INTEGER,
  PRIMARY KEY(id),
  FOREIGN KEY(class_id) REFERENCES class(id),
  FOREIGN KEY(teacher_id) REFERENCES teacher(id)
);
